.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Moritz Hoffmann <antiguru+deb@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH YKUSH2 1 "January  12, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ykush2 \- program to control the Yepkit YKUSH USB switchable hub
.SH SYNOPSIS
.nf
.BR ykush2 " -l"
.BR ykush2 " [-h \fIHUB\fP] {-d|-u} \fIPORT\fP"
.fi
.SH DESCRIPTION
This manual page documents briefly the
.B ykush2
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBykush2\fP is a program that allows one to control the Yepkit YKUSH USB switchable hub.
It can be used to enumerate hubs connected to a system and to switch on or off USB ports.
.SH OPTIONS
.TP
.B \-l
List available YKUSH USB hubs.
.TP
.B \-d ", " \-u \fIPORT\fP
Switch a specific port up or down. Specify port
.B 1
, 
.B 2
, 
.B 3
or
.B a
to switch all ports.
.TP
.B \-h \fIHUB\fP
Select the hub to control. The number can be obtained using the
.B \-l
option.
